name: adoptopenjdk-11

on:
  push:
    branches:
    - master
    paths:
    - 'adoptopenjdk-11/**'
    - github-action.sh
    - common.sh
    - 'tests/**'
    - '!tests/*.ps*'
    - '!tests/*.windows'
  pull_request:
    paths:
    - 'adoptopenjdk-11/**'
    - github-action.sh
    - common.sh
    - 'tests/**'
    - '!tests/*.ps*'
    - '!tests/*.windows'

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@v1.2.0
    - name: Check out code
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init
    - name: Build image
      run: ./github-action.sh adoptopenjdk-11 ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
