name: Docker Maven Image CI adoptopenjdk-8

on:
  push:
    paths:
    - 'adoptopenjdk-8/**'
    - github-action.sh
    - common.sh
    - 'tests/**'
    - '!tests/*.ps*'
  pull_request:
    paths:
    - 'adoptopenjdk-8/**'
    - github-action.sh
    - common.sh
    - 'tests/**'
    - '!tests/*.ps*'

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@v1.0.1
    - name: Check out code
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init
    - name: Build image
      run: ./github-action.sh adoptopenjdk-8 ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
