name: DIRECTORY

on:
  push:
    branches:
    - master
    paths:
      - '!LICENSE/**'
      - '!README-short.txt/**'
      - '!README.md/**'
      - '!amazoncorretto-11/**'
      - '!amazoncorretto-11-windowsservercore/**'
      - '!amazoncorretto-17/**'
      - '!amazoncorretto-19/**'
      - '!amazoncorretto-8/**'
      - '!amazoncorretto-8-windowsservercore/**'
      - '!azulzulu-11/**'
      - '!azulzulu-11-alpine/**'
      - '!azulzulu-11-windowsservercore/**'
      - '!azulzulu-17/**'
      - '!azulzulu-17-alpine/**'
      - '!common.sh/**'
      - '!coverage/**'
      - '!eclipse-temurin-11/**'
      - '!eclipse-temurin-11-alpine/**'
      - '!eclipse-temurin-11-focal/**'
      - '!eclipse-temurin-17/**'
      - '!eclipse-temurin-17-alpine/**'
      - '!eclipse-temurin-17-focal/**'
      - '!eclipse-temurin-19/**'
      - '!eclipse-temurin-19-alpine/**'
      - '!eclipse-temurin-19-focal/**'
      - '!eclipse-temurin-8/**'
      - '!eclipse-temurin-8-alpine/**'
      - '!eclipse-temurin-8-focal/**'
      - '!generate-stackbrew-library.sh/**'
      - '!github-action-generation.sh/**'
      - '!github-action.ps1/**'
      - '!ibm-semeru-11-focal/**'
      - '!ibm-semeru-17-focal/**'
      - '!ibmjava-8/**'
      - '!libericaopenjdk-11/**'
      - '!libericaopenjdk-11-alpine/**'
      - '!libericaopenjdk-11-debian/**'
      - '!libericaopenjdk-17/**'
      - '!libericaopenjdk-17-alpine/**'
      - '!libericaopenjdk-17-debian/**'
      - '!libericaopenjdk-8/**'
      - '!libericaopenjdk-8-alpine/**'
      - '!libericaopenjdk-8-debian/**'
      - '!logo.png/**'
      - '!microsoft-openjdk-11-ubuntu/**'
      - '!microsoft-openjdk-16-ubuntu/**'
      - '!microsoft-openjdk-17-ubuntu/**'
      - '!openjdk-11-nanoserver/**'
      - '!openjdk-11-windowsservercore/**'
      - '!openjdk-18/**'
      - '!openjdk-18-slim/**'
      - '!openjdk-8-nanoserver/**'
      - '!openjdk-8-windowsservercore/**'
      - '!publish.sh/**'
      - '!sapmachine-11/**'
      - '!sapmachine-17/**'
      - '!tags-for-dir.sh/**'
      - '!tests/**'
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - '!LICENSE/**'
      - '!README-short.txt/**'
      - '!README.md/**'
      - '!amazoncorretto-11/**'
      - '!amazoncorretto-11-windowsservercore/**'
      - '!amazoncorretto-17/**'
      - '!amazoncorretto-19/**'
      - '!amazoncorretto-8/**'
      - '!amazoncorretto-8-windowsservercore/**'
      - '!azulzulu-11/**'
      - '!azulzulu-11-alpine/**'
      - '!azulzulu-11-windowsservercore/**'
      - '!azulzulu-17/**'
      - '!azulzulu-17-alpine/**'
      - '!common.sh/**'
      - '!coverage/**'
      - '!eclipse-temurin-11/**'
      - '!eclipse-temurin-11-alpine/**'
      - '!eclipse-temurin-11-focal/**'
      - '!eclipse-temurin-17/**'
      - '!eclipse-temurin-17-alpine/**'
      - '!eclipse-temurin-17-focal/**'
      - '!eclipse-temurin-19/**'
      - '!eclipse-temurin-19-alpine/**'
      - '!eclipse-temurin-19-focal/**'
      - '!eclipse-temurin-8/**'
      - '!eclipse-temurin-8-alpine/**'
      - '!eclipse-temurin-8-focal/**'
      - '!generate-stackbrew-library.sh/**'
      - '!github-action-generation.sh/**'
      - '!github-action.ps1/**'
      - '!ibm-semeru-11-focal/**'
      - '!ibm-semeru-17-focal/**'
      - '!ibmjava-8/**'
      - '!libericaopenjdk-11/**'
      - '!libericaopenjdk-11-alpine/**'
      - '!libericaopenjdk-11-debian/**'
      - '!libericaopenjdk-17/**'
      - '!libericaopenjdk-17-alpine/**'
      - '!libericaopenjdk-17-debian/**'
      - '!libericaopenjdk-8/**'
      - '!libericaopenjdk-8-alpine/**'
      - '!libericaopenjdk-8-debian/**'
      - '!logo.png/**'
      - '!microsoft-openjdk-11-ubuntu/**'
      - '!microsoft-openjdk-16-ubuntu/**'
      - '!microsoft-openjdk-17-ubuntu/**'
      - '!openjdk-11-nanoserver/**'
      - '!openjdk-11-windowsservercore/**'
      - '!openjdk-18/**'
      - '!openjdk-18-slim/**'
      - '!openjdk-8-nanoserver/**'
      - '!openjdk-8-windowsservercore/**'
      - '!publish.sh/**'
      - '!sapmachine-11/**'
      - '!sapmachine-17/**'
      - '!tags-for-dir.sh/**'
      - '!tests/**'
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: DIRECTORY
    secrets: inherit
