name: DIRECTORY

on:
  push:
    paths:
      - '!LICENSE/**'
      - '!README-short.txt/**'
      - '!README.md/**'
      - '!amazoncorretto-11/**'
      - '!amazoncorretto-11-windowsservercore/**'
      - '!amazoncorretto-17/**'
      - '!amazoncorretto-8/**'
      - '!amazoncorretto-8-windowsservercore/**'
      - '!azulzulu-11/**'
      - '!azulzulu-11-alpine/**'
      - '!azulzulu-11-windowsservercore/**'
      - '!azulzulu-17/**'
      - '!azulzulu-17-alpine/**'
      - '!common.sh/**'
      - '!eclipse-temurin-11/**'
      - '!eclipse-temurin-11-alpine/**'
      - '!eclipse-temurin-17/**'
      - '!eclipse-temurin-17-alpine/**'
      - '!eclipse-temurin-18/**'
      - '!eclipse-temurin-18-alpine/**'
      - '!eclipse-temurin-8/**'
      - '!eclipse-temurin-8-alpine/**'
      - '!generate-stackbrew-library.sh/**'
      - '!github-action-generation.sh/**'
      - '!github-action.ps1/**'
      - '!ibm-semeru-11-focal/**'
      - '!ibm-semeru-17-focal/**'
      - '!ibmjava-8/**'
      - '!ibmjava-8-alpine/**'
      - '!libericaopenjdk-11/**'
      - '!libericaopenjdk-11-alpine/**'
      - '!libericaopenjdk-8/**'
      - '!libericaopenjdk-8-alpine/**'
      - '!logo.png/**'
      - '!microsoft-openjdk-11-ubuntu/**'
      - '!microsoft-openjdk-16-ubuntu/**'
      - '!microsoft-openjdk-17-ubuntu/**'
      - '!openjdk-11/**'
      - '!openjdk-11-nanoserver/**'
      - '!openjdk-11-slim/**'
      - '!openjdk-11-windowsservercore/**'
      - '!openjdk-18/**'
      - '!openjdk-18-slim/**'
      - '!openjdk-8/**'
      - '!openjdk-8-nanoserver/**'
      - '!openjdk-8-slim/**'
      - '!openjdk-8-windowsservercore/**'
      - '!publish.sh/**'
      - '!sapmachine-11/**'
      - '!sapmachine-17/**'
      - '!tags-for-dir.sh/**'
      - '!tests/**'
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - '!LICENSE/**'
      - '!README-short.txt/**'
      - '!README.md/**'
      - '!amazoncorretto-11/**'
      - '!amazoncorretto-11-windowsservercore/**'
      - '!amazoncorretto-17/**'
      - '!amazoncorretto-8/**'
      - '!amazoncorretto-8-windowsservercore/**'
      - '!azulzulu-11/**'
      - '!azulzulu-11-alpine/**'
      - '!azulzulu-11-windowsservercore/**'
      - '!azulzulu-17/**'
      - '!azulzulu-17-alpine/**'
      - '!common.sh/**'
      - '!eclipse-temurin-11/**'
      - '!eclipse-temurin-11-alpine/**'
      - '!eclipse-temurin-17/**'
      - '!eclipse-temurin-17-alpine/**'
      - '!eclipse-temurin-18/**'
      - '!eclipse-temurin-18-alpine/**'
      - '!eclipse-temurin-8/**'
      - '!eclipse-temurin-8-alpine/**'
      - '!generate-stackbrew-library.sh/**'
      - '!github-action-generation.sh/**'
      - '!github-action.ps1/**'
      - '!ibm-semeru-11-focal/**'
      - '!ibm-semeru-17-focal/**'
      - '!ibmjava-8/**'
      - '!ibmjava-8-alpine/**'
      - '!libericaopenjdk-11/**'
      - '!libericaopenjdk-11-alpine/**'
      - '!libericaopenjdk-8/**'
      - '!libericaopenjdk-8-alpine/**'
      - '!logo.png/**'
      - '!microsoft-openjdk-11-ubuntu/**'
      - '!microsoft-openjdk-16-ubuntu/**'
      - '!microsoft-openjdk-17-ubuntu/**'
      - '!openjdk-11/**'
      - '!openjdk-11-nanoserver/**'
      - '!openjdk-11-slim/**'
      - '!openjdk-11-windowsservercore/**'
      - '!openjdk-18/**'
      - '!openjdk-18-slim/**'
      - '!openjdk-8/**'
      - '!openjdk-8-nanoserver/**'
      - '!openjdk-8-slim/**'
      - '!openjdk-8-windowsservercore/**'
      - '!publish.sh/**'
      - '!sapmachine-11/**'
      - '!sapmachine-17/**'
      - '!tags-for-dir.sh/**'
      - '!tests/**'
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: DIRECTORY
    secrets: inherit
