name: DIRECTORY

on:
  push:
    branches:
    - master
    paths:
    - '!LICENSE/**'
    - '!README-short.txt/**'
    - '!README.md/**'
    - '!amazoncorretto-11/**'
    - '!amazoncorretto-11-windowsservercore/**'
    - '!amazoncorretto-16/**'
    - '!amazoncorretto-17/**'
    - '!amazoncorretto-8/**'
    - '!amazoncorretto-8-windowsservercore/**'
    - '!azulzulu-11/**'
    - '!azulzulu-11-alpine/**'
    - '!azulzulu-11-windowsservercore/**'
    - '!azulzulu-14/**'
    - '!azulzulu-14-alpine/**'
    - '!common.sh/**'
    - '!eclipse-temurin-11/**'
    - '!eclipse-temurin-16/**'
    - '!eclipse-temurin-17/**'
    - '!eclipse-temurin-8/**'
    - '!generate-stackbrew-library.sh/**'
    - '!github-action-generation.sh/**'
    - '!github-action.ps1/**'
    - '!github-action.sh/**'
    - '!ibmjava-8/**'
    - '!ibmjava-8-alpine/**'
    - '!libericaopenjdk-11/**'
    - '!libericaopenjdk-11-alpine/**'
    - '!libericaopenjdk-8/**'
    - '!libericaopenjdk-8-alpine/**'
    - '!logo.png/**'
    - '!microsoft-openjdk-11-ubuntu/**'
    - '!microsoft-openjdk-16-ubuntu/**'
    - '!microsoft-openjdk-17-ubuntu/**'
    - '!openjdk-11/**'
    - '!openjdk-11-nanoserver/**'
    - '!openjdk-11-slim/**'
    - '!openjdk-11-windowsservercore/**'
    - '!openjdk-17/**'
    - '!openjdk-17-slim/**'
    - '!openjdk-8/**'
    - '!openjdk-8-nanoserver/**'
    - '!openjdk-8-slim/**'
    - '!openjdk-8-windowsservercore/**'
    - '!publish.sh/**'
    - '!tests/**'
    - '!tests/*.windows'
  pull_request:
    paths:
    - '!LICENSE/**'
    - '!README-short.txt/**'
    - '!README.md/**'
    - '!amazoncorretto-11/**'
    - '!amazoncorretto-11-windowsservercore/**'
    - '!amazoncorretto-16/**'
    - '!amazoncorretto-17/**'
    - '!amazoncorretto-8/**'
    - '!amazoncorretto-8-windowsservercore/**'
    - '!azulzulu-11/**'
    - '!azulzulu-11-alpine/**'
    - '!azulzulu-11-windowsservercore/**'
    - '!azulzulu-14/**'
    - '!azulzulu-14-alpine/**'
    - '!common.sh/**'
    - '!eclipse-temurin-11/**'
    - '!eclipse-temurin-16/**'
    - '!eclipse-temurin-17/**'
    - '!eclipse-temurin-8/**'
    - '!generate-stackbrew-library.sh/**'
    - '!github-action-generation.sh/**'
    - '!github-action.ps1/**'
    - '!github-action.sh/**'
    - '!ibmjava-8/**'
    - '!ibmjava-8-alpine/**'
    - '!libericaopenjdk-11/**'
    - '!libericaopenjdk-11-alpine/**'
    - '!libericaopenjdk-8/**'
    - '!libericaopenjdk-8-alpine/**'
    - '!logo.png/**'
    - '!microsoft-openjdk-11-ubuntu/**'
    - '!microsoft-openjdk-16-ubuntu/**'
    - '!microsoft-openjdk-17-ubuntu/**'
    - '!openjdk-11/**'
    - '!openjdk-11-nanoserver/**'
    - '!openjdk-11-slim/**'
    - '!openjdk-11-windowsservercore/**'
    - '!openjdk-17/**'
    - '!openjdk-17-slim/**'
    - '!openjdk-8/**'
    - '!openjdk-8-nanoserver/**'
    - '!openjdk-8-slim/**'
    - '!openjdk-8-windowsservercore/**'
    - '!publish.sh/**'
    - '!tests/**'
    - '!tests/*.windows'

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@v1.2.0
    - name: Check out code
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init
    - name: Build image
      run: ./github-action.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
